version: '3.8'

services:
  face-navigator:
    build: .
    container_name: face-navigator-app
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      # X11 socket for GUI display
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Optional: Mount config for persistence
      - ./config.json:/app/config.json:ro
      # Optional: Mount facial landmarks file to avoid re-downloading
      - ./shape_predictor_68_face_landmarks.dat:/app/shape_predictor_68_face_landmarks.dat:ro
    devices:
      # Camera access
      - /dev/video0:/dev/video0
    network_mode: host
    privileged: false
    # Grant access to video group
    group_add:
      - video
    restart: unless-stopped
    command: ["python3", "face_navigator.py"]

  # Alternative service for debugging with video preview
  face-navigator-debug:
    build: .
    container_name: face-navigator-debug
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config.json:/app/config.json:ro
      - ./shape_predictor_68_face_landmarks.dat:/app/shape_predictor_68_face_landmarks.dat:ro
    devices:
      - /dev/video0:/dev/video0
    network_mode: host
    privileged: false
    group_add:
      - video
    restart: "no"
    command: ["python3", "face_navigator.py", "--show-video"]
    profiles:
      - debug